# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: file-validation.proto for package 'FileValidationPackage'

require 'grpc'
require './file-validation_pb'

module FileValidationPackage
  module FileValidation
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'FileValidationPackage.FileValidation'

      rpc :validateSize, ::FileValidationPackage::ValidateSizeRequest, ::FileValidationPackage::Response
      rpc :validateFileMimeType, ::FileValidationPackage::ValidateMimeTypeRequest, ::FileValidationPackage::Response
      rpc :helloService, ::Google::Protobuf::Empty, ::FileValidationPackage::GreetingResponse
    end

    Stub = Service.rpc_stub_class
  end
end
