# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hello.proto for package ''

require 'grpc'
require '/Users/himanshuyadav/Desktop/Learn/grpc-learn/client/ruby/hello_pb.rb'

module NewsService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'NewsService'

    rpc :GetAllNews, ::Empty, ::NewsList
  end

  Stub = Service.rpc_stub_class
end
