# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

require 'google/protobuf'


descriptor_data = "\n\x0bhello.proto\"B\n\x04News\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x11\n\tpostImage\x18\x04 \x01(\t\"\x07\n\x05\x45mpty\"\x1f\n\x08NewsList\x12\x13\n\x04news\x18\x01 \x03(\x0b\x32\x05.News20\n\x0bNewsService\x12!\n\nGetAllNews\x12\x06.Empty\x1a\t.NewsList\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

News = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("News").msgclass
Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Empty").msgclass
NewsList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NewsList").msgclass
